var PRINCIPLES={
"respect-user-preferences":{title:"Respect user preferences",status:"",desc:"The most fundamental principle for web usability: adapt to the user's stated and system-level preferences (theme, motion, contrast) rather than imposing one fixed experience. Read the signals the platform already provides and adjust.",how:"Probes prefers-color-scheme (dark mode), prefers-reduced-motion, and forced-colors via Chrome DevTools Protocol. A vision agent then checks whether the page actually adapts to each signal."},
"be-inclusive":{title:"Be inclusive",status:"",desc:"Usable with assistive technology and a keyboard, plus a comparable inclusive experience beyond bare conformance: sufficient colour contrast, names and roles on controls, labelled form fields, sensible heading/landmark structure, visible focus order, legible text. WCAG is the floor; inclusive design is the ceiling.",how:"Lighthouse accessibility audit plus axe violations (colour contrast, labels, landmarks, focus order, heading structure). Vision agent corroborates."},
"be-fast-and-stable":{title:"Be fast and stable",status:"",desc:"Load quickly and stay visually stable: good Core Web Vitals (LCP, INP, CLS), a light main thread, and no layout jank from late-arriving content. Speed and stability are part of modern UX, not separate from it.",how:"Lighthouse performance score plus Core Web Vitals (LCP, CLS, TBT) from Lighthouse and CDP traces. Vision agent checks for visible layout shift and slow loading."},
"follow-best-practices":{title:"Follow best practices",status:"",desc:"Soundly built and served: no console errors or uncaught exceptions, a valid doctype and charset, correctly sized images, no deprecated APIs, well-structured non-repetitive CSS and HTML.",how:"Lighthouse best-practices dimension: console errors, doctype/charset, image sizing, deprecated APIs, HTTPS."},
"be-private-and-secure":{title:"Be private and secure",status:"",desc:"Protects users by default. Served over HTTPS with a sensible Content-Security-Policy, secure/SameSite cookies, no over-collection or leaky third parties, permission prompts requested in context, data-minimised analytics.",how:"HTTPS, Content-Security-Policy headers, secure/SameSite cookies, permission-prompt timing, and third-party tracking inspection via CDP and vision."},
"be-discoverable":{title:"Be discoverable",status:"",desc:"Discoverable and shareable: a descriptive title and meta description, crawlable links, a valid robots configuration, a viewport meta tag, and meaningful link text.",how:"Title, meta description, viewport meta, crawlable links, and robots config (the Lighthouse SEO dimension). Non-JS discoverability is measured as the % of content visible without JavaScript."},
"be-agent-ready":{title:"Be agent ready",status:"",desc:"Forward-looking. The site exposes its capabilities to AI agents and on-device intelligence in a structured, safe way (WebMCP tools, agentic forms, semantic markup) and uses on-device inference appropriately. Emerging, so judged as opportunity rather than obligation.",how:"Structured data, semantic HTML, machine-readable content, and WebMCP/agent tool exposure. Judged as opportunity, not obligation."},
"be-sustainable":{title:"Be sustainable",status:"",desc:"Resource-efficient. Respects a page-weight budget, ships optimised assets at appropriate resolutions, avoids wasteful background work and over-fetching, and prefers the lightest technique that achieves the result.",how:"Page weight, asset optimisation, redundant requests, and wasted background work. Backed by the W3C Web Sustainability Guidelines."},
"maximize-content-reduce-noise":{title:"Maximise content, reduce noise",status:"",desc:"Prioritise the user's content by eliminating visual clutter and intrusive interruptions. Avoid pop-ups and banners that obscure content; use the right semantic, dismissible primitives instead of heavy custom chrome.",how:"Intrusive pop-ups, banners, cookie walls, and custom chrome that obscure content. Vision-based judgement."},
"be-internationalised":{title:"Be internationalised",status:"",desc:"Works for users in any language and locale. Correct lang/dir, logical CSS properties, locale-aware dates, numbers and currencies, translation-ready markup, and time handling that survives time zones and DST.",how:"Correct lang/dir attributes, logical CSS properties, locale-aware formatting, and translation-ready markup."},
"be-memory-efficient":{title:"Be memory-efficient",status:"",desc:"Should not leak memory or grow its footprint without bound, especially under repeated interaction. A session that gets slower and heavier the longer it is used is a broken experience even if the first paint was fast.",how:"Heap-diff: baseline snapshot → 3 scroll/navigation cycles → forced garbage collection → final snapshot. Sites retaining more than 5 MB after GC are flagged as leaks."},
"adapt-to-the-form-factor":{title:"Adapt to the form factor",status:"",desc:"Account for the form factor users actually access the site from. A modern experience genuinely adapts layout and interaction across viewports and input types using modern responsive techniques.",how:"Responsive layout across viewports, horizontal-overflow check, touch-target sizing, and viewport meta presence via CDP."},
"support-core-task-success":{title:"Support core task success",status:"",desc:"Help people accomplish the thing they came to do. Understand the offer, find the path, complete the flow, see system state, and recover. A page can pass technical checks and still fail if the purpose is unclear.",how:"Active interaction test: the probe finds the primary action (search box, sign-up, buy button, hero CTA), clicks it, and checks whether the flow visibly progresses to a meaningful next state."},
"provide-guided-navigation":{title:"Provide guided navigation",status:"",desc:"Help users understand where they are and guide their attention through the experience, using state-aware UI and positioning rather than leaving them to orient themselves.",how:"Desktop and mobile screenshot re-audit of visible primary navigation, search, current-location or active-state cues, content hierarchy, consent-wall obstruction, and clear paths to the page's primary actions. Results record pass, issues, or not-applicable with confidence and evidence; this run did not exercise multi-step navigation flows."},
"implement-natural-interactions":{title:"Implement natural interactions",status:"",desc:"Make interactions feel intuitive and physical. Use modern declarative motion APIs so movement reflects how things move in the real world, rather than abrupt state swaps or heavy hand-rolled JavaScript.",how:"Active feature detection: checks for View Transitions API usage (elements with view-transition-name), scroll-driven animations (animation-timeline), and whether motion respects prefers-reduced-motion."},
"be-trustworthy":{title:"Be trustworthy",status:"",desc:"Honest and humane. No dark patterns (confirmshaming, forced continuity, disguised ads, nagging consent walls), honest defaults, clear pricing and consent, easy reversal of actions, predictable controls, and humane error handling.",how:"Desktop and mobile screenshot re-audit for obstructive consent walls, confirmshaming, disguised advertising, misleading defaults, unclear pricing or consent, and visible recovery paths. Results are limited to the captured homepage state; account, checkout, cancellation, and reversal flows were not exercised in this run."},
"be-resilient":{title:"Be resilient",status:"",desc:"Core content and primary flows work under adverse conditions: no JS, slow or offline network, older or non-Baseline browsers. Modern features are progressive enhancements with graceful fallbacks.",how:"CDP discoverability comparison with JavaScript enabled and disabled, including visible-content coverage and JS-shell detection. Current aggregate results measure no-JS resilience only; offline behavior, installability, and older-browser degradation require separate evidence and are not claimed as tested."}
};
